language: python
python:
  - 2.7
env:
  - TWISTED=14.0.0 HTTPBIN_URL=http://httpbin.org/
  - TWISTED=15.0.0 HTTPBIN_URL=http://httpbin.org/
  - TWISTED=latest HTTPBIN_URL=http://httpbin.org/
install:
  - pip install -U pip
  - "[ $TWISTED = latest ] || pip install Twisted==$TWISTED"
  - pip install .
script: trial test_txrequests.py
